name: "Testing yaml"

on:
	workflow_dispatch:
	push:
		branches:
			- main

# Jobs
# cat /proc/cpuinfo
# 
jobs:
  check-specs:
    runs-on: ubuntu-latest
    steps:
    - name: Check CPU Specs
      run: cat /proc/cpuinfo
      
