name: "Testing yaml"

on:
  workflow_dispatch:
    inputs:
      custom_command:
        description: 'Custom command'
        required: true

jobs:
  check-specs:
    runs-on: ubuntu-latest
    steps:
    - name: Check Specs
      run: ${{ inputs.custom_command }}
      
